//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Tablas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public decimal Id { get; set; }
        public decimal PersonaId { get; set; }
        public System.DateTime FechaContratacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public decimal Salario { get; set; }
        public decimal RolId { get; set; }
        public string Correo { get; set; }
        public string Clave { get; set; }
        public string Telefono { get; set; }
        public decimal SedeId { get; set; }
    
        public virtual Persona PERSONAS { get; set; }
        public virtual Rol ROLES { get; set; }
        public virtual Sede SEDES { get; set; }
    }
}
