//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Tablas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.DETALLEFACTURAS = new HashSet<DetalleFactura>();
        }
    
        public decimal Id { get; set; }
        public decimal ClienteId { get; set; }
        public decimal Total { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public decimal SedeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFactura> DETALLEFACTURAS { get; set; }
        public virtual Cliente CLIENTES { get; set; }
        public virtual Sede SEDES { get; set; }
    }
}
